config/routes.rb
Rails.application.routes.draw do
  resources :lies
  resources :truths do
    member do
      post 'accept'
    end

    collection do
      get 'review'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'trump#gen'
end

app/controllers/lies_controller.rb
class LiesController < ApplicationController
  before_action :set_lie, only: [:show, :edit, :update, :destroy]

  # GET /lies
  # GET /lies.json
  def index
    @lies = Lie.all
  end

  # GET /lies/1
  # GET /lies/1.json
  def show
  end

  # GET /lies/new
  def new
    order = params[:model_order]&.to_i || 2
    sentences = params[:sentences]&.to_i || 3
    puts "Generating new Lie with order: #{order} sentences: #{sentences}."
    text, ref_ids = Trump.get_sentences(sentences, order)
    @lie = Lie.new(text: text.join(' '), model_order: order, model_version: Trump.model_version)
    @reference_texts = Trump.sample_ref_texts(ref_ids.uniq)
  end

  # GET /lies/1/edit
  def edit
  end

  # POST /lies
  # POST /lies.json
  def create
    @lie = Lie.new(lie_params)

    respond_to do |format|
      if @lie.save
        format.html { redirect_to action: 'index', notice: 'Lie was successfully created.' }
        format.json { render :show, status: :created, location: @lie }
      else
        format.html { render :new }
        format.json { render json: @lie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lies/1
  # PATCH/PUT /lies/1.json
  def update
    respond_to do |format|
      if @lie.update(lie_params)
        format.html { redirect_to @lie, notice: 'Lie was successfully updated.' }
        format.json { render :show, status: :ok, location: @lie }
      else
        format.html { render :edit }
        format.json { render json: @lie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lies/1
  # DELETE /lies/1.json
  def destroy
    @lie.destroy
    respond_to do |format|
      format.html { redirect_to lies_url, notice: 'Lie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lie
      @lie = Lie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lie_params
      params.require(:lie).permit(:text, :model_version, :model_order, :state)
    end
end

app/helpers/lies_helper.rb
module LiesHelper
end

app/views/lies/edit.html.erb
<h1>Editing Lie</h1>

<%= form_with(model: @lie, local: true) do |form| %>
  <% if @lie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lie.errors.count, "error") %> prohibited this lie from being saved:</h2>

      <ul>
      <% @lie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :model_version %>
    <%= form.text_field :model_version, readonly: true %>
  </div>

  <div class="field">
    <%= form.label :model_order %>
    <%= form.number_field :model_order, readonly: true %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, readonly: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @lie %> |
<%= link_to 'Back', lies_path %>

app/views/lies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Text</th>
      <th>Model version</th>
      <th>Model order</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lies.each do |lie| %>
      <tr>
        <td><%= lie.text %></td>
        <td><%= lie.model_version %></td>
        <td><%= lie.model_order %></td>
        <td><%= lie.state %></td>
        <td><%= link_to 'Show', lie %></td>
        <td><%= link_to 'Edit', edit_ly_path(lie) %></td>
        <td><%= link_to 'Destroy', lie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lie', new_ly_path %>

app/views/lies/new.html.erb
<h1>New Lie</h1>
<div class="container">
  <div class="row">
    <div class="col-8">
      <%= form_with(model: @lie, local: true) do |form| %>
        <div class="form-group">
          <%= form.label :text %>
          <%= form.text_area :text, class: 'form-control', resize: 'none', rows: 5 %>
        </div>

        <div class="field">
          <%= form.text_field :model_version, readonly: true, hidden: true %>
        </div>

        <div class="field">
          <%= form.number_field :model_order, readonly: true, hidden: true %>
        </div>

        <div>
          <%= form.submit class:'btn-primary' %>
        </div>
      <% end %>

      <hr />
      <h4>Regenerate text - adjust model params</h4>
      <form action='/lies/new' method='get'>
        <div class="form-group">
          <label for="model_order">Model Order</label>
          <select name='model_order'>
            <% Trump.model_orders.each do |model_order| %>
              <option value='<%= model_order %>' <%= 'selected' if @lie.model_order == model_order %>><%= model_order %></option>
            <% end %>
          </select>
        </div>
        <div class="form-group">
          <label for="sentences">Sentences</label>
          <input type="number" id="sentences" name="sentences" value="3"/>
        </div>
        <div>
          <input type="submit" value="Regenerate Text" class="btn-secondary">
        </div>
      </form>
      <%= link_to 'Back', lies_path %>
    </div>
    <div class="col-4">
      <h3>Inspired by</h3>
      <div class="overflow-auto" style="max-height: 500px;" >
      <% @reference_texts.each do |reference_text| %>
        <div class="card">
          <div class="card-body">
            <%= reference_text %>
          </div>
        </div>
      <% end %>
      </div>

    </div>
  </div>
</div>

app/views/lies/review.html.erb
<p id="notice"><%= notice %></p>

<h1>Reivew Lies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Text</th>
      <th>Model version</th>
      <th>Model order</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lies.each do |lie| %>
      <tr>
        <td><%= lie.text %></td>
        <td><%= lie.model_version %></td>
        <td><%= lie.model_order %></td>
        <td><%= lie.state %></td>
        <td><%= link_to 'Show', lie %></td>
        <td><%= link_to 'Edit', edit_ly_path(lie) %></td>
        <td><%= link_to 'Destroy', lie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lie', new_ly_path %>

app/views/lies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @lie.text %>
</p>

<p>
  <strong>Model version:</strong>
  <%= @lie.model_version %>
</p>

<p>
  <strong>Model order:</strong>
  <%= @lie.model_order %>
</p>

<p>
  <strong>State:</strong>
  <%= @lie.state %>
</p>

<%= link_to 'Edit', edit_ly_path(@lie) %> |
<%= link_to 'Back', lies_path %>