config/routes.rb
Rails.application.routes.draw do
  resources :lies
  resources :truths do
    member do
      post 'accept'
    end

    collection do
      get 'review'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'trump#gen'
end

app/models/truth.rb
class Truth < ApplicationRecord
end

app/controllers/truths_controller.rb
class TruthsController < ApplicationController
  before_action :set_truth, only: [:show, :edit, :update, :destroy, :accept]

  PAGE_SIZE = 20

  # GET /truths
  # GET /truths.json
  def index
    @page = params[:page]&.to_i || 1
    offset = (@page - 1) * PAGE_SIZE
    @truths = Truth.where(state: 'ACCEPTED').limit(PAGE_SIZE).offset(offset)
  end

  # GET /truths/review
  def review
    @page = params[:page]&.to_i || 1
    offset = (@page - 1) * PAGE_SIZE
    @truths = Truth.where(state: 'REVIEW').limit(PAGE_SIZE).offset(offset)
  end

  # GET /truths/1
  # GET /truths/1.json
  def show
  end

  # GET /truths/new
  def new
    @truth = Truth.new
  end

  # GET /truths/1/edit
  def edit
  end

  # POST /truths
  # POST /truths.json
  def create
    @truth = Truth.new(truth_params)

    respond_to do |format|
      if @truth.save
        format.html { redirect_to @truth, notice: 'Truth was successfully created.' }
        format.json { render :show, status: :created, location: @truth }
      else
        format.html { render :new }
        format.json { render json: @truth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /truths/1
  # PATCH/PUT /truths/1.json
  def update
    respond_to do |format|
      if @truth.update(truth_params)
        format.html { redirect_to @truth, notice: 'Truth was successfully updated.' }
        format.json { render :show, status: :ok, location: @truth }
      else
        format.html { render :edit }
        format.json { render json: @truth.errors, status: :unprocessable_entity }
      end
    end
  end

  def accept
    @truth.update(state: 'ACCEPTED')
    redirect_to review_truths_url, notice: 'Truth was accepted.'
  end

  # DELETE /truths/1
  # DELETE /truths/1.json
  def destroy
    @truth.destroy
    respond_to do |format|
      format.html { redirect_to review_truths_url, notice: 'Truth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truth
      @truth = Truth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def truth_params
      params.require(:truth).permit(:text, :sent, :tweet_id, :retweet_count, :state)
    end
end

app/helpers/truths_helper.rb
module TruthsHelper
end

app/views/truths/_form.html.erb
<%= form_with(model: truth, local: true) do |form| %>
  <% if truth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(truth.errors.count, "error") %> prohibited this truth from being saved:</h2>

      <ul>
      <% truth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :sent %>
    <%= form.datetime_select :sent %>
  </div>

  <div class="field">
    <%= form.label :tweet_id %>
    <%= form.text_field :tweet_id %>
  </div>

  <div class="field">
    <%= form.label :retweet_count %>
    <%= form.number_field :retweet_count %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/truths/edit.html.erb
<h1>Editing Truth</h1>

<%= render 'form', truth: @truth %>

<%= link_to 'Show', @truth %> |
<%= link_to 'Back', truths_path %>

app/views/truths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Truths</h1>

<table class="table">
  <thead>
    <tr>
      <th>Text</th>
      <th>Sent</th>
      <th>Tweet</th>
      <th>Retweet count</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @truths.each do |truth| %>
      <tr>
        <td><%= truth.text %></td>
        <td><%= truth.sent %></td>
        <td><%= truth.tweet_id %></td>
        <td><%= truth.retweet_count %></td>
        <td><%= truth.state %></td>
        <td><%= link_to 'Show', truth %></td>
        <td><%= link_to 'Edit', edit_truth_path(truth) %></td>
        <td><%= link_to 'Destroy', truth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Truth', new_truth_path %>

app/views/truths/new.html.erb
<h1>New Truth</h1>

<%= render 'form', truth: @truth %>

<%= link_to 'Back', truths_path %>

app/views/truths/review.html.erb
<p id="notice"><%= notice %></p>

<h1>Review Potential Truth Cards</h1>

<table class="table">
  <thead>
    <tr>
      <th>Text</th>
      <th>Retweet count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @truths.each do |truth| %>
      <tr>
        <td><%= truth.text %></td>
        <td><a href="https://www.twitter.com/statuses/<%= truth.tweet_id %>" target="_"><%= truth.retweet_count %></a></td>
        <td><%= truth.state %></td>
        <td><%= link_to 'Edit', edit_truth_path(truth) %></td>
        <td><%= link_to 'Accept', accept_truth_path(truth), method: :post %></td>
        <td><%= link_to 'Reject', truth, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Next Page', review_truths_path(page: @page+1) %>

<br>
<%= link_to 'View Accepted Truth Cards', truths_path %>

app/views/truths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @truth.text %>
</p>

<p>
  <strong>Sent:</strong>
  <%= @truth.sent %>
</p>

<p>
  <strong>Tweet:</strong>
  <%= @truth.tweet_id %>
</p>

<p>
  <strong>Retweet count:</strong>
  <%= @truth.retweet_count %>
</p>

<p>
  <strong>State:</strong>
  <%= @truth.state %>
</p>

<%= link_to 'Edit', edit_truth_path(@truth) %> |
<%= link_to 'Back', truths_path %>