config/routes.rb
Rails.application.routes.draw do
  resources :lies
  resources :truths do
    member do
      post 'accept'
    end

    collection do
      get 'review'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'trump#gen'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trump - Truths and a Lie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Trump - Truth and Lies</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Truth Cards", truths_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Lie Cards", lies_path, class: 'nav-link' %>
      </li>
      <li>
        |
      </li>
      <li class="nav-item">
        <%= link_to "Create Truth", review_truths_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Create Lie", new_ly_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

<main role="main" class="container">
  <div class="jumbotron">
    <%= yield %>
  </div>
</main>

  </body>
</html>